### ISSUE TITLE
DYNOTYPE not exported in extra/datadog.sh

### ISSUE THREAD

**Issue by mfly** [DataDog/heroku-buildpack-datadog#121] opened 2019-07-05 11:28 UTC
Prerun script from the official docs https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script uses `DYNOTYPE` environment variable. However this variable is not set by the buildpack.
Possible fix would be to add `export` in https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L43.

**Comment by arapulido** [comment] 2019-09-11 12:23
The prerun script gets sourced in the `datadog.sh` script, so exporting is not needed. Can you explain a bit more how you are using this script and why it is not working for you?

**Comment by arapulido** [comment] 2019-10-07 09:19
@mfly I am closing this for now, as I cannot reproduce the issue. If you still have issues, please, reopen.

**Closed by arapulido** 2019-10-07 09:19 UTC
