### ISSUE TITLE
Current Heroku Agent Setup instructions mention Major version 7 - however 6.17 is pulled and installed

### ISSUE THREAD

**Issue by christx2** [DataDog/heroku-buildpack-datadog#176] opened 2020-02-20 16:41 UTC
Hello there, the instructions for the Agent Setup for Heroku in the initial setup https://app.datadoghq.eu/account/settings#agent/heroku   
list heroku config:add DD_AGENT_MAJOR_VERSION=7

However this is not the case when the Heroku App is Build and Deployed the latest version is actually 6.17.0 from the repo that the same document lists, perhaps update the document or move the repo to be version 7

$ agent-wrapper version
Agent 6.17.0 - Commit: 6eb25b4 - Serialization version: 4.19.0 - Go version: go1.12.9

**Comment by arapulido** [comment] 2020-02-20 16:45
Thanks for your issue @christx2 ! I will investigate this asap. 

One question, do you have `DD_AGENT_VERSION` set to any value in your application?

Thanks,
Ara

**Comment by arapulido** [comment] 2020-02-20 16:54
@christx2 also, take into account that upgrading your version requires to clear your cache before recompiling: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#upgrading-and-slug-recompilation

This could also be the issue

**Comment by arapulido** [comment] 2020-02-20 17:04
I cannot reproduce it in my setup :(

So, to recap:

1. Can you check that you don't have `DD_AGENT_VERSION` set to `6.17.0-1` ? This environment variable takes precedence
2. If you don't have `DD_AGENT_VERSION` set to anything, clear your  build cache and try again.

If you still get 6.17 after doing what I suggest above, let us know so we continue investigating.

**Comment by christx2** [comment] 2020-02-20 17:36
Hello there, i have purged several times and recommitted the empty repo, explicitly unset also the variable

heroku config:unset DD_AGENT_MAJOR_VERSION

git commit --allow-empty -m "Purge cache"

heroku repo:purge_cache -a morning-tundra-95593

 git push heroku master

DD_DYNO_HOST:              true
DD_SERVICE_NAME:           datadog-test-christ
DD_SITE:                   datadoghq.eu
DD_TAGS:                   env:production

heroku run bash agent-wrapper version
http://localhost:8126
Agent 6.17.0 - Commit: 6eb25b4 - Serialization version: 4.19.0 - Go version: go1.12.9

there is no versioning in my ruby app or its manifests

**Comment by arapulido** [comment] 2020-02-20 17:45
Mmm, I am confused now, it looks like in this latest comment, you don't have `DD_AGENT_MAJOR_VERSION` set to 7, in which case it will correctly pull `6.17`.

Also, can you paste the logs of the heroku build that are related to the Datadog agent installation, please?

**Comment by christx2** [comment] 2020-02-20 17:51
Hello, it was set to 7 - so now i explicitly set it back and re-ran the purge and deploy
heroku config:set DD_AGENT_MAJOR_VERSION=7
Setting DD_AGENT_MAJOR_VERSION and restarting ⬢ morning-tundra-95593... done, v74
DD_AGENT_MAJOR_VERSION: 7

Starting Datadog Agent on morning-tundra-95593.run.8272
Starting Datadog Trace Agent on morning-tundra-95593.run.8272
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   414  100   414    0     0   6088      0 --:--:-- --:--:-- --:--:--  6088
2020-02-20 17:50:08 UTC | CORE | INFO | (cmd/agent/app/run.go:181 in StartAgent) | Starting Datadog Agent v6.17.0
2020-02-20 17:50:09 UTC | CORE | INFO | (cmd/agent/app/run.go:212 in StartAgent) | Hostname is: morning-tundra-95593.run.8272
2020-02-20 17:50:09 UTC | CORE | INFO | (pkg/api/security/security.go:135 in FetchAuthToken) | Saved a new authentication token to /app/.apt/etc/datadog-agent/auth_token
  % T2020-02-20 17:50:09 UTC | TRACE | INFO | (pkg/util/log/log.go:482 in func1) | Loaded configuration: /app/.apt/etc/datadog-agent/datadog.yaml
otal    % Received % Xferd  Average Speed   Time    Time     Time  Current
           2020-02-20 17:50:09 UTC | TRACE | INFO | (pkg/trace/agent/run.go:118 in Run) | Trace agent running on host morning-tundra-95593.run.8272
2020-02-20 17:50:09 UTC | TRACE | INFO | (pkg/trace/api/api.go:153 in Start) | Listening for traces at http://localhost:8126
                      Dload  Upload   Total   Spent    Left  Speed
100   412    0     0  100   412      0   2423 --:--:-- --:--:-- --:--:--  2423

**Comment by arapulido** [comment] 2020-02-20 18:01
Glad it was solved! I will close this now.

**Closed by arapulido** 2020-02-20 18:01 UTC
