### ISSUE TITLE
Agent is complaining about DD_API_KEY even tho it is set 

### ISSUE THREAD

**Issue by adi-reforge** [DataDog/heroku-buildpack-datadog#327] opened 2023-03-02 19:39 UTC
Hello, 

We are running datadog in our heroku environment with another app called Envkey which is the secret store for all our config vars. When a new build is initiated :

1) Envkey pulls all the config vars from envkey app and sets them as environment variables (this includes setting DD_API_KEY) 
2) Second buildpack is datadog agent which runs after the envkey step and it fails with the following error when I attach to a dyno in console : 

DD_API_KEY environment variable not set. Run: heroku config:add DD_API_KEY=<your API key>"

Which I believe is coming from your shell script line 107

"if [ -z "$DD_API_KEY" ]; then
  echo "DD_API_KEY environment variable not set. Run: heroku config:add DD_API_KEY=<your API key>"
  DISABLE_DATADOG_AGENT=1
fi"

I am logged on to the heroku dyno and when I grep for DD_API_KEY I see the environment value : 

~ $ printenv | grep DD_API_KEY
DD_API_KEY=<value hidden>

Any ideas why the agent is unable to get the API key from environment variable?

**Comment by arapulido** [comment] 2023-03-03 09:36
Hello! Have you set `heroku config:set ENVKEY_BUILD_PHASE_EXPORT=1`  (https://docs-v2.envkey.com/docs/heroku#build-phase-variables) ?

**Comment by arapulido** [comment] 2023-03-03 09:40
Also, what version of the envkey buildpack are you using? Can you put here the output of `heroku buildpacks` ?

**Comment by adi-reforge** [comment] 2023-03-03 14:55
1. https://github.com/envkey/envkey-heroku-buildpack#v3
2. https://github.com/DataDog/heroku-buildpack-datadog.git
3. heroku/nodejs
4. heroku/ruby

and yes `ENVKEY_BUILD_PHASE_EXPORT=1` is set

**Comment by arapulido** [comment] 2023-03-06 12:10
@adi-reforge I think that the issue is that `.profile.d` scripts are run in alphabetical order by Heroku, so the their `envkey.sh` script is run after the `datadog.sh` script. This is not ideal, as buildpacks need to have access to env variables for them to work correctly, so `envkey.sh` should always run first.

I have opened a PR against the `envkey` buildpack to fix this: https://github.com/envkey/envkey-heroku-buildpack/pull/4

You can try the fix by replacing your `envkey` buildpack with my fork to test it: `https://github.com/arapulido/envkey-heroku-buildpack#v3`

If it fixes the issue, you could ping `envkey` to review the pull request to fix it on their side. Thanks!

**Comment by adi-reforge** [comment] 2023-03-06 20:26
Sounds good I am in touch with @danenania regarding this and he will let me know when that PR is merged. Its not ultra pressing but I ll give the fork a try as well. 

Thank you for your prompt response and help

**Comment by arapulido** [comment] 2023-03-08 08:04
@adi-reforge hello! I saw that the PR was merged. Can you confirm that the change solves your issue, please?

**Closed** 2023-03-10 09:42 UTC
