### ISSUE TITLE
Trace agent does not run

### ISSUE THREAD

**Issue by matthewbennink** [DataDog/heroku-buildpack-datadog#31] opened 2018-02-20 16:39 UTC
Received the following error message, likely due to agent being updated to the latest version (`6.0.0~rc.2-1_amd64` in this case).

```
cp: cannot stat ‘/app/.apt/etc/datadog-agent/trace-agent.conf.example’: No such file or directory
```

**Comment by izakp** [comment] 2018-02-21 12:18
Looks like the trace agent cannot start

**Comment by stevenleeg** [comment] 2018-02-22 22:42
I've been seeing this issue as well (and haven't been seeing APM traces come in). Any updates on what's going on here?

**Comment by daveyu** [comment] 2018-02-24 23:15
It seems like this change in [6.0.0-rc.1](https://github.com/DataDog/datadog-agent/releases/tag/6.0.0-rc.1) is the cause: 

> On Linux and macOS, the trace-agent and process-agent now read their configuration from the main datadog.yaml file (located, by default on Linux, at /etc/datadog-agent/datadog.yaml).

I see APM traces resume after pinning to 6.0.0~beta.9-1: `heroku config:set DD_AGENT_VERSION=6.0.0~beta.9-1_amd64`

**Comment by teeratpitakrat** [comment] 2018-03-02 20:13
Looks like it cannot find the 6.0.0~beta.9-1 package. Is there a way to fix this?

```
remote:        Installing pinned version "6.0.0~beta.9-1_amd64"
remote: ls: cannot access '/app/tmp/cache/apt/cache/archives/datadog-agent_1%3a6.0.0~beta.9-1_amd64.deb': No such file or directory
remote: -----> ERROR: Version "6.0.0~beta.9-1_amd64" was not found.
remote:  !     Push rejected, failed to compile Sysstat app.
```

**Comment by jyee** [comment] 2018-03-12 18:13
The beta packages are no longer available as of buildpack 1.0.0 when the deb repo was changed to `stable 6`. If you still need access to beta releases, you should fork this repo, then modify `etc/datadog.list` (https://github.com/DataDog/heroku-buildpack-datadog/blob/master/etc/datadog.list) to use `deb http://apt.datadoghq.com/ beta main`

**Comment by cosmith** [comment] 2018-03-13 13:38
I'm having trouble getting APM to work on Heroku too, and I see the same error in my logs:

```
2018-03-13T13:37:04.980735+00:00 heroku[web.1]: State changed from up to starting
2018-03-13T13:37:06.182482+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-03-13T13:37:06.408552+00:00 heroku[web.1]: Process exited with status 143
2018-03-13T13:37:06.214743+00:00 app[web.1]: 2018-03-13 13:37:06 UTC | INFO | (start.go:106 in func2) | Received signal 'terminated', shutting down...
2018-03-13T13:37:06.214931+00:00 app[web.1]: 2018-03-13 13:37:06 UTC | INFO | (runner.go:149 in Stop) | Runner is shutting down...
2018-03-13T13:37:06.217158+00:00 app[web.1]: 2018-03-13 13:37:06 UTC | INFO | (forwarder.go:271 in Stop) | DefaultForwarder stopped
2018-03-13T13:37:33.392068+00:00 heroku[web.1]: Starting process with command `ddtrace-run waitress-serve --port=52382 --threads 8 --channel-timeout=10 truckfly.wsgi:application`
2018-03-13T13:37:36.056080+00:00 app[web.1]: cp: cannot stat '/app/.apt/etc/datadog-agent/trace-agent.conf.example': No such file or directory
2018-03-13T13:37:36.405432+00:00 app[web.1]: 2018-03-13 13:37:36 UTC | INFO | (start.go:156 in StartAgent) | Starting Datadog Agent v6.0.3
2018-03-13T13:37:36.405629+00:00 app[web.1]: 2018-03-13 13:37:36 UTC | INFO | (start.go:174 in StartAgent) | Hostname is: dashdoc-test
2018-03-13T13:37:36.410899+00:00 app[web.1]: 2018-03-13 13:37:36 UTC | INFO | (security.go:131 in FetchAuthToken) | Saved a new authentication token to /app/.apt/etc/datadog-agent/auth_token
2018-03-13T13:37:36.105216+00:00 app[web.1]: Starting Datadog Agent on dyno web.1
2018-03-13T13:37:37.395527+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (start.go:191 in StartAgent) | GUI server port -1 specified: not starting the GUI.
2018-03-13T13:37:37.395555+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (forwarder.go:232 in Start) | DefaultForwarder started (1 workers), sending to 1 endpoint(s): "https://6-0-3-app.agent.datadoghq.com" (1 api key(s))
2018-03-13T13:37:37.395558+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (start.go:231 in StartAgent) | logs-agent disabled
2018-03-13T13:37:37.395583+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (tagger.go:77 in Init) | starting the tagging system
2018-03-13T13:37:37.407940+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (udp.go:63 in Listen) | dogstatsd-udp: starting to listen on 127.0.0.1:8125
2018-03-13T13:37:37.896635+00:00 app[web.1]: 2018-03-13 13:37:37 UTC | INFO | (runner.go:92 in NewRunner) | Runner started with 1 workers.
2018-03-13T13:37:38.377567+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (collector.go:51 in NewCollector) | Embedding Python 2.7.14 (default, Mar  9 2018, 12:15:24) [GCC 4.7.2]
2018-03-13T13:37:38.503365+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | ERROR | (loader.go:38 in NewPythonCheckLoader) | Unable to import Python module: checks
2018-03-13T13:37:38.503400+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (loaders.go:48 in func1) | Failed to instantiate Python Check Loader: unable to initialize AgentCheck module
2018-03-13T13:37:38.503441+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (file.go:68 in Collect) | File Configuration Provider: searching for configuration files at: /app/.apt/etc/datadog-agent/conf.d
2018-03-13T13:37:38.689783+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (file.go:68 in Collect) | File Configuration Provider: searching for configuration files at: /app/.apt/opt/datadog-agent/bin/agent/dist/conf.d
2018-03-13T13:37:38.689932+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | WARN | (file.go:72 in Collect) | Skipping, open /app/.apt/opt/datadog-agent/bin/agent/dist/conf.d: no such file or directory
2018-03-13T13:37:38.690230+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | ERROR | (autoconfig.go:248 in getChecksFromConfigs) | Unable to load the check: unable to load any check from config 'disk'
2018-03-13T13:37:38.690301+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | ERROR | (autoconfig.go:248 in getChecksFromConfigs) | Unable to load the check: unable to load any check from config 'network'
2018-03-13T13:37:38.690358+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check cpu
2018-03-13T13:37:38.690462+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check cpu with an interval of 15s
2018-03-13T13:37:38.690517+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check file_handle
2018-03-13T13:37:38.690583+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check file_handle with an interval of 15s
2018-03-13T13:37:38.690656+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check io
2018-03-13T13:37:38.690705+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check io with an interval of 15s
2018-03-13T13:37:38.690798+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check load
2018-03-13T13:37:38.690846+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check load with an interval of 15s
2018-03-13T13:37:38.690900+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check memory
2018-03-13T13:37:38.691190+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check memory with an interval of 15s
2018-03-13T1
3:37:38.691246+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check ntp
2018-03-13T13:37:38.691521+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check ntp with an interval of 15s
2018-03-13T13:37:38.691578+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (autoconfig.go:267 in schedule) | Scheduling check uptime
2018-03-13T13:37:38.691657+00:00 app[web.1]: 2018-03-13 13:37:38 UTC | INFO | (scheduler.go:72 in Enter) | Scheduling check uptime with an interval of 15s
2018-03-13T13:37:39.285320+00:00 app[web.1]: ERROR:ddtrace.writer:cannot send services to localhost:8126: [Errno 111] Connection refused
2018-03-13T13:37:39.958450+00:00 app[web.1]: 2018-03-13 13:37:39 UTC | INFO | (serializer.go:180 in SendMetadata) | Sent host metadata payload, size: 2258 bytes.
2018-03-13T13:37:41.198187+00:00 app[web.1]: 2018-03-13 13:37:41 UTC | INFO | (transaction.go:133 in Process) | Successfully posted payload to "https://6-0-3-app.agent.datadoghq.com/intake/?api_key=*************************b2631", the agent will only log transaction success every 20 transactions
2018-03-13T13:37:41.910030+00:00 app[web.1]: Serving on http://0.0.0.0:52382
2018-03-13T13:37:42.295126+00:00 app[web.1]: cannot send services to localhost:8126: [Errno 111] Connection refused
```

**Comment by cosmith** [comment] 2018-03-13 14:35
I tried using `beta main` as suggested but no luck, it looks like it's not downloading the correct package.

<details>
<pre>
-----> Sysstat app detected
-----> Updating apt caches for dependencies
       Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
       Get:2 http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease [46.4 kB]
       Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
       Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
       Get:5 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main amd64 Packages [145 kB]
       Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
       Get:7 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
       Get:8 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [589 kB]
       Get:9 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [406 kB]
       Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [957 kB]
       Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [766 kB]
       Fetched 14.7 MB in 2s (6,478 kB/s)
       Reading package lists...
-----> Installing dependencies
       Reading package lists...
       Building dependency tree...
       Suggested packages:
         lm-sensors snmp-mibs-downloader
       The following NEW packages will be installed:
         libpci-dev libpci3 libsensors4 libsensors4-dev libsnmp-base libsnmp30
       0 upgraded, 6 newly installed, 0 to remove and 23 not upgraded.
       Need to get 1,164 kB of archives.
       After this operation, 4,725 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpci3 amd64 1:3.3.1-1.1ubuntu1.1 [24.5 kB]
       Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpci-dev amd64 1:3.3.1-1.1ubuntu1.1 [42.7 kB]
       Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libsensors4 amd64 1:3.4.0-2 [28.4 kB]
       Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libsnmp-base all 5.7.3+dfsg-1ubuntu4.1 [224 kB]
       Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libsnmp30 amd64 5.7.3+dfsg-1ubuntu4.1 [811 kB]
       Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 libsensors4-dev amd64 1:3.4.0-2 [33.8 kB]
       Fetched 1,164 kB in 1s (600 kB/s)
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
       Installing libpci-dev
       Installing libpci3
       Installing libsensors4
       Installing libsensors4-dev
       Installing libsnmp-base
       Installing libsnmp30
-----> Updating apt caches for Datadog Agent
       Ign:1 http://apt.datadoghq.com beta InRelease
       Get:2 http://apt.datadoghq.com beta Release [5,599 B]
       Get:3 http://apt.datadoghq.com beta Release.gpg [819 B]
       Ign:3 http://apt.datadoghq.com beta Release.gpg
       Get:4 http://apt.datadoghq.com beta/main amd64 Packages [5,219 B]
       Get:5 http://apt.datadoghq.com beta/main all Packages [393 B]
       Fetched 12.0 kB in 0s (78.9 kB/s)
       Reading package lists...
W: GPG error: http://apt.datadoghq.com beta Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B4593018387EEAF
W: The repository 'http://apt.datadoghq.com beta Release' is not signed.
-----> Installing Datadog Agent
       Reading package lists...
       Building dependency tree...
       The following NEW packages will be installed:
         datadog-agent
       0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
       Need to get 93.0 MB of archives.
       After this operation, 324 MB of additional disk space will be used.
       WARNING: The following packages cannot be authenticated!
         datadog-agent
       Get:1 http://apt.datadoghq.com beta/main amd64 datadog-agent amd64 1:6.0.3~rc.2-1 [93.0 MB]
       Fetched 93.0 MB in 2s (44.8 MB/s)
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
       Installing pinned version "6.0.0~beta.9-1_amd64"
ls: cannot access '/app/tmp/cache/apt/cache/archives/datadog-agent_1%3a6.0.0~beta.9-1_amd64.deb': No such file or directory
-----> ERROR: Version "6.0.0~beta.9-1_amd64" was not found.
 !     Push rejected, failed to compile Sysstat app.
 !     Push failed
</pre>
</details>

**Comment by teeratpitakrat** [comment] 2018-03-13 15:08
Same for me here.
- Using the newest version, the image can be created but at startup I get: `cp: cannot stat '/app/.apt/etc/datadog-agent/trace-agent.conf.example'` and no trace is collected.
- Using the old beta version (with modified datadog.list) I get: `ERROR: Version "6.0.0~beta.9-1_amd64" was not found.` and the image cannot be built.

**Comment by jyee** [comment] 2018-03-14 22:09
Hey everyone, just thought I'd drop a quick update:

1. The `cp` issue is an easy fix, but unrelated to the trace agent not starting.
2. I'm working with our APM team to determine why the trace agent isn't starting automatically.
3. If you need tracing immediately, I've got a *temporary fix* on the `jyee/apm` branch that manually starts the trace agent. To use that, set your buildpack to `https://github.com/DataDog/heroku-buildpack-datadog.git#jyee/apm`

Sorry for the inconvenience. I hope to have this fully resolved in the coming days.

**Comment by jyee** [comment] 2018-03-15 16:18
Hey everyone, I just pushed 1.1.0! Notably this release:

1. Removes the `cp` issue, since the trace agent uses the main datadog.yaml
2. Includes code to start the Trace Agent. Previously the main Datadog Agent would start the Trace Agent, but this has been moved to systemd and upstart services for linux installs. This broke Heroku because we're not using systemd (no root access to install new services).
3. The seelog error from my temporary fix still remains. Currently the Trace Agent does not allow you to specify a log location (basically it's hardcoded to `/var/log/datadog`). I've made a request to the APM team to change this and will update the buildpack when that's available.

**Closed by jyee** 2018-03-15 16:18 UTC
Labels: bug

**Comment by cosmith** [comment] 2018-03-16 08:35
Hi @jyee, thanks for the quick response. I tried your 1.1.0 release but I can't get APM to work... 
What's weird is that the logs seem to be fine yet nothing appears on https://app.datadoghq.com/apm/install
```
2018-03-16T08:33:25.501142+00:00 app[web.1]: 2018-03-16 08:33:25 INFO (service_mapper.go:59) - total number of tracked services: 3
2018-03-16T08:33:25.501164+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:33:40.850288+00:00 app[web.1]: 2018-03-16 08:33:40 INFO (trace_writer.go:89) - flushed trace payload to the API, time:342.664547ms, size:11764 bytes
2018-03-16T08:33:40.851607+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:33:45.585665+00:00 app[web.1]: 2018-03-16 08:33:45 INFO (trace_writer.go:89) - flushed trace payload to the API, time:80.965759ms, size:8021 bytes
2018-03-16T08:33:45.585694+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:33:55.674270+00:00 app[web.1]: 2018-03-16 08:33:55 INFO (trace_writer.go:89) - flushed trace payload to the API, time:155.967764ms, size:27819 bytes
2018-03-16T08:33:55.674367+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:33:55.767436+00:00 app[web.1]: 2018-03-16 08:33:55 INFO (stats_writer.go:73) - flushed stat payload to the API, time:248.821226ms, size:28257 bytes
2018-03-16T08:33:55.767526+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:34:05.589180+00:00 app[web.1]: 2018-03-16 08:34:05 INFO (stats_writer.go:73) - flushed stat payload to the API, time:82.503263ms, size:2731 bytes
2018-03-16T08:34:05.589317+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:34:15.501578+00:00 app[web.1]: 2018-03-16 08:34:15 INFO (receiver.go:324) - [lang:python lang_version:3.6.4 interpreter:CPython tracer_version:0.11.0] -> traces received: 6, traces dropped: 0, traces filtered: 0, traces amount: 335036 bytes, services received: 18, services amount: 618 bytes
2018-03-16T08:34:15.501635+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-03-16T08:34:15.665081+00:00 app[web.1]: 2018-03-16 08:34:15 INFO (stats_writer.go:73) - flushed stat payload to the API, time:155.404321ms, size:23423 bytes
2018-03-16T08:34:15.665207+00:00 app[web.1]: seelog internal error: mkdir /var/log/datadog/: read-only file system
```

I can share more info in private if you want.

**Comment by irabinovitch** [comment] 2018-03-16 08:37
Thanks @cosmith.  If you're able to send the additional details to support@datadoghq.com we'll dig in.

**Comment by cosmith** [comment] 2018-03-16 08:43
@irabinovitch @jyee nevermind it started working right after this message... sorry for the trouble and thanks for the fix!
