### ISSUE TITLE
check-disk error

### ISSUE THREAD

**Issue by ronalddas** [DataDog/heroku-buildpack-datadog#91] opened 2019-01-14 14:09 UTC
Hi, I am running heroku python buildpack v146.Running Python 3.6 I have installed datadog agent on it, its reporting correctly. the only issue is that, the agents keeps on sending Error to stdout, which messes up my logs. I have set DD_LOG_LEVEL=CRITICAL, but still it keeps on outputting.
Here is the Error
`Error: Error running check disk: [{"message": "[Errno 2] No such file or directory: '/etc/mtab'", "traceback": "Traceback (most recent call last):\n  File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py\", line 374, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py\", line 59, in check\n    self.collect_metrics_psutil()\n  File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py\", line 70, in collect_metrics_psutil\n    for part in psutil.disk_partitions(all=True):\n  File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/__init__.py\", line 1990, in disk_partitions\n    return _psplatform.disk_partitions(all)\n  File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/_pslinux.py\", line 1162, in disk_partitions\n    partitions = cext.disk_partitions(mtab_path)\nOSError: [Errno 2] No such file or directory: '/etc/mtab'\n"}]`

**Comment by jyee** [comment] 2019-01-14 20:09
@ronalddas I'm not able to reproduce this. 

Can you ensure that you're setting the level correctly by running `heroku config`?
Also, your dyno should be able to see `/etc/mtab` if you cannot, you might have a malformed slug. To regenerate a slug without pushing new code, you'll need to generate an empty commit and push to heroku:
```
git commit --allow-empty -m "Force rebuild"
git push heroku master
```

**Comment by arapulido** [comment] 2020-01-03 09:12
I will close this now, but feel free to reopen if you are still seeing the issue with the latest version of the buildpack

**Closed by arapulido** 2020-01-03 09:12 UTC
